export enum NotificationTypeEnum {
  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_ASSIGNED = 'REQUEST_ASSIGNED',
  REQUEST_STATUS_CHANGED = 'REQUEST_STATUS_CHANGED',
  REQUEST_COMMENTED = 'REQUEST_COMMENTED',
  REQUEST_CANCELED = 'REQUEST_CANCELED',
}
