import { z } from 'zod';

export const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']),
  PORT: z.coerce.number().int().positive(),
  DATABASE_URL: z.string().url(),
  JWT_ACCESS_SECRET: z.string().min(1),
  JWT_REFRESH_SECRET: z.string().min(1),
  JWT_ACCESS_TTL: z.coerce.number().int().positive(),
  JWT_REFRESH_TTL: z.coerce.number().int().positive(),
  PGOPTIONS: z.string().optional(),
  PRISMA_APPLY_SESSION_TIMEOUTS: z.string().optional(),
  HTTP_BODY_LIMIT: z.string().optional(),
  THROTTLE_TTL: z.coerce.number().int().positive().optional(),
  THROTTLE_LIMIT: z.coerce.number().int().positive().optional(),
  THROTTLE_AUTH_TTL: z.coerce.number().int().positive().optional(),
  THROTTLE_AUTH_LIMIT: z.coerce.number().int().positive().optional(),
  DEFAULT_PAGE_SIZE: z.coerce.number().int().positive().optional(),
  MAX_PAGE_SIZE: z.coerce.number().int().positive().optional(),
  REQUEST_METRICS_ENABLED: z.string().optional(),
  REQUEST_METRICS_INTERVAL_MS: z.coerce.number().int().positive().optional(),
  REQUEST_METRICS_SAMPLE_SIZE: z.coerce.number().int().positive().optional(),
  HTTP_SERVER_TIMEOUT_MS: z.coerce.number().int().positive().optional(),
  HTTP_HEADERS_TIMEOUT_MS: z.coerce.number().int().positive().optional(),
  HTTP_KEEP_ALIVE_TIMEOUT_MS: z.coerce.number().int().positive().optional(),
  WS_CORS_ORIGINS: z.string().optional(),
  WS_LOG_CONNECTIONS: z.string().optional(),
  QUEUE_ENABLED: z.string().optional(),
  QUEUE_HOST: z.string().optional(),
  QUEUE_PORT: z.coerce.number().int().optional(),
  QUEUE_PASSWORD: z.string().optional(),
  STORAGE_ENDPOINT: z.string().optional(),
  STORAGE_REGION: z.string().optional(),
  STORAGE_BUCKET: z.string().optional(),
  STORAGE_ACCESS_KEY_ID: z.string().optional(),
  STORAGE_SECRET_ACCESS_KEY: z.string().optional(),
  PLATFORM_API_KEY: z.string().optional(),
  PLATFORM_SUPERADMIN_EMAIL: z.string().optional(),
  PLATFORM_SUPERADMIN_PASSWORD: z.string().optional(),
});
